version = 1

test_patterns = [
    "tests/**",
    "test_*.py"
]

exclude_patterns = [
  
]

[[analyzers]]
name = 'python'
enabled = true
runtime_version = '3.x.x'

  [analyzers.meta]
  max_line_length = 150

[[analyzers]]
name = "test-coverage"
enabled = true
