version = 1

test_patterns = [
    "tests/**",
    "test_*.py"
]

exclude_patterns = [
  
]

[[analyzers]]
name = 'python'
enabled = true
runtime_version = '3.x.x'

name = "test-coverage"
enabled = true

[analyzers.meta]
max_line_length = 150
