frame:
    slideshow_delay: 30000
    root_folder: media
    font: 14
    compass: mpu6050
    flip_rotation: true
    google_maps: 3294239jdsfwd

players:
   Holiday Photo Player:
        type: photo_player
        folder: italy
		shuffle: true

    Family Photo Player:
        type: photo_player
        folder: personal
		shuffle: false
        
    My dashboard:
        type: dashboard
