frame:
    slideshow_delay: 30000
    media_folder: media

players:
    Photo Player:
        type: photo_player
        folder: photos
    Fritz Monitor:
        type: photo_player
        folder: fritz-monitor
    Pi Tank Watcher:
        type: photo_player
        folder: pi-tank-watcher
    Video Player:
        type: video_player
        folder: video
