frame:
    slideshow_delay: 30000
    root_folder: media
    font: 14
    compass: mpu6050
    flip_rotation: true
    shuffle: true


players:
    Photo Player:
        type: photo_player
        folder: photos
    Video Player:
        type: video_player
        folder: video
